name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install Dependencies
      run: npm install
      working-directory: /projects/daily-jokes-linux

    - name: Restart Application
      run: pm2 restart app
      working-directory: /projects/daily-jokes-linux

    - name: Pull Latest Code
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd /projects/daily-jokes-linux
        git pull origin main
